apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  namespace: grafana
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "beekeeping2026"
  influxdb-token: "shields-farm-influxdb-token-2026"
