apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: influxdb
type: Opaque
stringData:
  admin-password: "beekeeping2026"
  admin-token: "shields-farm-influxdb-token-2026"
  organization: "shields-farm"
  bucket: "broodminder"
